[
    {
        "title": "Mexican Burger",
        "date": "2 January, 2022",
        "img": "https://i.ibb.co/SR3vvhT/blog-Post3.jpg",
        "shortDesc": "Burgers are one of most favourite comfort foods we have. They are easy to cook and so delicious to eat! Burgers are the most amazing on-the-go recipes, just a few ingredients in place and you are good to go!...",
        "rating": "4.8",
        "PrepTime": "20 minutes",
        "CookTime": "20 minutes",
        "TotalTime": "40 minutes",
        "Servings": "4",
        "Ingredients": ["6 guajillo peppers", "3 cloves garlic", "2 avocados, chopped", "1 lime, juiced", "1 jalapeno pepper, diced", "2 Tbsp chopped fresh cilantro", "1 ½ tsp salt, divided", "2 Tbsp chopped onion", "1 cup water", "1 Tbsp brown sugar", "1 Tbsp tomato paste", "1 Tbsp cider vinegar", "1 ancho chili, toasted and ground (or chili powder)", "1 lb ground beef", "1 tsp pepper", "8 slices queso fresco", "4 burger buns", "Tortilla chips", "4 slices tomato", "4 slices onion"],
        "Directions": ["1. Heat a skillet on medium-high. Add guajillo peppers and toast for 5 minutes. Remove peppers and set aside. Place garlic in the pan, with skin still intact and toast on both sides until lightly charred, about 3 minutes. Remove and set aside.",
            "2. Cut the stems off the guajillo peppers and discard seeds. Use scissors to cut the peppers into small pieces in a medium bowl. Pour boiling water over top until the peppers are covered and set aside to rehydrate for 15 minutes.",
            "3. Meanwhile, make the jalapeno guacamole by mashing together the avocado, lime juice, diced jalapeno, cilantro and ¼ tsp salt. Set aside until serving.",
            "4. Once the guajillo peppers are rehydrated, remove the skins from the garlic and place in the container of a blender. Add chopped onion, water, brown sugar, tomato paste, cider vinegar and ¼ tsp salt. Strain the guajillo peppers and add them to the blender. Pulse on high until smooth, then pass the guajillo ketchup through a sieve. Discard the seeds and skin, and reserve the ketchup for serving.",
            "5. Preheat BBQ on high heat. Form the ground beef into 4 patties and season with ancho chili, remaining salt and pepper. Place on the grill and cook for 5 minutes per side or until medium-well. Add queso fresco once the burgers are flipped. Toast the buns for the final minute of cooking. Remove the buns and burgers and allow to rest for 3 minutes.",
            "6. To assemble, spread a spoonful of jalapeno guacamole on the bottom bun. Top with a handful of tortilla chips and place burger on top. Spoon guajillo ketchup on the burger, then top with one slice of tomato and onion. Smother in additional guajillo ketchup and finish with the top bun.",
        ]
    },
    {
        "title": "Kabab",
        "date": "25 December, 2021",
        "img": "https://i.ibb.co/jT7kvgj/blog-Post2.jpg",
        "shortDesc": "Gorgeous kababs that make an amazing meal with bold flavours and is packed full of freshness! These quick & easy minty kababs served alongside raita are perfect for a relaxed meal your family and friends will all want to tuck into...",
        "rating": "5",
        "PrepTime": "30 minutes",
        "CookTime": "15 minutes",
        "TotalTime": "45 minutes",
        "Servings": "2",
        "Ingredients": ["Oven temp: 375 F- 205 C", "2 cups keema (minced mutton/lamb/beef)", "1 tbsp vinegar", "2 tbsp fenugreek leaves, chopped", "1/2 tbsp garlic paste", "1/2 tbsp ginger paste", "1 1/2 tbsp salt", "1/4 tbsp black pepper, powdered", "1/4 tbsp garam masala", "2 tbsp coriander leaves, chopped", "1 tbsp green chillies, finely chopped", "Skewers to make the kebabs", "Oil for brushing", "chaat masala", "lemon wedges"],
        "Directions": ["1.In a large bowl, mix lamb mince with few Tbsp of vinegar, fenugreek leaves.",
            "2.Then add garlic paste, ginger paste, salt and black pepper as per taste.", "3.Add chopped coriander leaves and green chillies.", "4.Refrigerate the meat mixture, covered, to marinate for at least 5 hours.", "5.About 25 minutes before serving, shape the meat mixture into long 'tubes' around the skewers (seekhs) and place on to a grill over a drip tray or into the pre-heated oven (also on a drip tray) and bake for 20-25 minutes.", "6.Brush them with oil and cook for another 2 minutes.", "7.Using oven mittens or a cloth, carefully push the kebab from one end, on to a serving dish.", "8.Garnish with the chaat masala, onions, lemons and serve along with green chutney."
        ],
    },
    {
        "title": "Chips & Fried Chicken",
        "date": "27 November, 2021",
        "img": "https://i.ibb.co/89jZtLk/blog-Post1.jpg",
        "shortDesc": "Crunchy potato chips are a natural coating to create a crispy crust for baked chicken breasts everyone in the family will love for dinner...",
        "longDesc": "",
        "rating": "4.8",
        "PrepTime": "15 minutes",
        "CookTime": "30 minutes",
        "TotalTime": "45 minutes",
        "Servings": "1",
        "Ingredients": ["4 boneless, skinless chicken breasts, sliced", "1 cup flour(125 g)", "1 tablespoon salt", "1 tablespoon pepper", "1 tablespoon garlic powder", "1 tablespoon onion powder", "4 eggs, beaten", "2 cups potato chip(70 g), of preference, crushed"],
        "Directions": ["1. In a large ziploc bag, add the flour, salt, pepper, garlic powder, onion powder, and stir to combine.", "2. In a wide dish, beat the eggs", "3. In a separate ziploc bag, crush your favorite type of potato chip.", "4. Preheat oven to 425°F (220°C).", "5. To bread the chicken, first place the chicken slices in the bag of seasoned flour and shake until completely coated, then pour the chicken into the egg mixture and stir with a slotted spoon until completely coated.", "6. Place the egg-coated chicken and place into the bag of crushed chips and shake until they are completely coated.", "7. Pour the potato chip-coated chicken onto a parchment paper-lined sheet tray.", "8. Bake for 25 minutes, or until the chicken reaches an internal temperature of 165°F (74°C) and is golden brown.", "9. Serve with your favorite dipping sauce.", "10. Enjoy!"],
    },
    {
        "title": "Vegetable Ramen",
        "date": "05 July, 2021",
        "img": "https://i.ibb.co/bWc3pC4/blog-Post4.webp",
        "shortDesc": "Easy homemade chicken ramen, with a flavorful broth, roasted chicken, fresh veggies, lots of noodles, and a soft cooked egg. Inspired by traditional Japanese ramen, but on the table in under an hour...",
        "longDesc": "",
        "rating": "4.7",
        "PrepTime": "25 minutes",
        "CookTime": "10 minutes",
        "TotalTime": "35 minutes",
        "Servings": "2",
        "Ingredients": ["1 tablespoon sesame oil", "3 teaspoons ginger, grated", "4 teaspoons garlic, minced", "3 tablespoons soy sauce", "2 tablespoons mirin or rice wine vinegar", "4 cups vegetable stock (or chicken stock)", "½ cup fresh shiitake mushrooms", "2 eggs", "1 cup baby spinach", "2 (3 oz) packs dried ramen noodles", "hot sauce, to taste (optional)", "½ cup green onions/scallions, sliced", "1 cup carrots, shredded", "sesame seeds (optional, for topping)"],
        "Directions": ["1. Heat the sesame oil in a large pot over medium heat. Add the garlic and ginger and cook for a couple minutes until soft and fragrant. Stir in the soy sauce and mirin and cook for another minute. Add the stock and bring to a simmer. Simmer for 5 minutes.", "2. Add the mushrooms and simmer for another 10 minutes.", "3. Meanwhile, bring a small pot of water to a boil. Add the eggs and cook for exactly 7 minutes for a slightly runny yoke or 8 minutes for a soft yolk. Remove eggs from the pot and place in a bowl of ice water to stop the cooking process. After a few minutes, peel the shells off carefully and slice the eggs in half, lengthwise. Set aside.", "4. Bring another pot of water to a boil. Add the spinach and cook for about a minute, until just wilted. Remove from pot and run under cold water to stop the cooking process. Drain and set aside.", "5. Add ramen noodles to stock mixture and cook 2-3 minutes or according to package instructions. Add some hot sauce, to taste (optional).", "6. Divide the soup into 2 large bowls.", "7. Top with an egg, spinach, carrots and green onions. Sprinkle with sesame seeds (optional) and serve immediately."],
    },
    {
        "title": "Mutton Briyani",
        "date": "25 February, 2021",
        "img": "https://i.ibb.co/fSs4vVr/blog-Post5.jpg",
        "shortDesc": "Briyani is a rice-based dish made with spices and chicken, mutton, fish, eggs or vegetables. The name is derived from the Persian word bre, meaning fried, roasted .It was one of the most famous dishes in the kitchen of the Mughal Emperors...",
        "rating": "5",
        "PrepTime": "10 minutes",
        "CookTime": "50 minutes",
        "TotalTime": "60 minutes",
        "Servings": "2",
        "Ingredients": ["1 Star anise", "500 gms basmati rice, blanched", "2 Bay leaves", "2 Black cardamom", "2 tsp black cumin seeds", "6 Black peppercorn", "6 Green cardamom", "2 Cinnamon sticks", "6 Cloves", "1 tsp fennel", "1/4 Jaiphal", "1 Javitri", "3 tsp Salt", "1 kg mutton (cut in 2 inches pieces, preferably front leg part and avoid shoulder cut)", "1 tbsp garam masala", "1 tbsp garlic paste", "1 tbsp ginger paste", "3 tbsp raw papaya paste", "4 tbsp hung curd", "1 Lemon (juiced)", "Coriander powder", "Cumin powder", "1 tbsp red chilli powder", "1 tsp salt", "4 onions, sliced", "2 tomatoes, chopped", "1/4 cup milk (warm)", "Ghee", "Saffron strands", "Rose water"],
        "Directions": ["1. To the mutton add the beaten curd, ginger-garlic paste, raw papaya paste, chilli powder, salt, lemon juice, garam masala. Allow the mutton to marinate for 3 hours. Slice 2 onions very thinly. Separate the slices. In a pan or kadai add oil and fry the onion slices till nicely brown. Take care not to burn them. Fry in small batches. Do not put all the slices at a time, that will lead to lumpy messy onions.", "2. Make sure all the onion slices frying are dipped in oil, if needed add more oil. Keep stirring continuously but gently for an even brown color. Take the fried onions out with a slotted spoon or ladle. Keep them on a paper-towel lined plate. This crispy brown fried onion slices are called Barista. Heat ghee in a thick-bottomed pan. Add remaining sliced onions and green chillies. Cook, stirring continuously, till onions are light golden brown. Add ginger paste and garlic paste and mix well. Add marinated mutton and cook on high heat for seven to eight minutes. Add coriander powder, cumin powder and red chilli powder. Mix thoroughly.", "3. Stir in three cups of water, bring it to a boil, reduce heat and cook covered till mutton is almost cooked. Add tomatoes, salt, garam masala powder and fresh coriander leaves. Cook for 15 minutes on medium heat, stirring occasionally. The ghee would be separated from the spices and there should not be any watery gravy to the meat. Use only good quality long grain Basmati rice. Soak the rice for 20 minutes in water. Wash well till the water runs clear. Drain all the water. In a small piece of cloth take cardamom, cinnamon, cloves, javitri, jaiphal, black peppercorn, shahi jeera, star anise and tie a knot to make a bag (potli). Bring 750 ml water to boil, add rice, bay leaf, salt and potli, cover and cook till rice is done 1/3rd. Drain the water & remove the whole masala potli. Take 1/4th cup warm milk in a cup and dissolve saffron strands in the milk.", "4. Cover and wait for 20 minutes. Add rose water and kewra essence in the milk. Mix well and cover. Keep aside. Take a large heavy bottom pan with tight fitting lid. Add 2tbsp ghee to the pan. Melt the ghee on low heat. Turn and rotate the pan carefully so the ghee can coat the bottom and sides of the pan. Switch off the heat. Add a layer of cooked rice, then cooked meat pieces, sprinkle saffron water, add fried onion slices and ghee.", "5. Cover with chopped pudina and coriander  onion and slit green chillies and juice of half a lemon."],
    },
    {
        "title": "Fish Fried",
        "date": "18 November, 2020",
        "img": "https://i.ibb.co/DMDJm9H/blog-Post6.jpg",
        "shortDesc": "A fish fry is a meal containing battered or breaded fried fish. It usually also includes french fries, coleslaw, mudpuppies, lemon slices, tartar sauce, hot sauce, malt vinegar and dessert...",
        "rating": "4.9",
        "PrepTime": "10 minutes",
        "CookTime": "30 minutes",
        "TotalTime": "40 minutes",
        "Servings": "2",
        "Ingredients": ["Vegetable oil, for frying", "1 1/2 to 2 pounds fresh cod", "Salt and pepper", "1 /2 cup all-purpose unbleached flour", "2 large eggs", "2 tablespoons cold water, a splash", "2 cups plain bread crumbs", "1/2 teaspoon dried mustard powder", "1/4 teaspoon cayenne pepper, a few pinches", "Wedged lemons and malt vinegar for topping"],
        "Directions": ["1. Pour 2-inches of vegetable oil into a large skillet. Place skillet over large burner and heat oil over medium high heat. To check if the oil is hot enough, drop in 1-inch cube of white bread. The bread should brown in a 40 count.", "2. Cut cod into 4 servings, 6 to 8-ounce portions and season with salt and pepper. Place a couple of scoops of flour in a pie tin. Combine egg and water in second tin. Season plain bread crumbs and mustard and cayenne in the third tin. Coat fish in flour, then egg, and then bread crumbs. Gently set coated fish into hot oil and fry 5 minutes on each side until medium golden brown in color.", "3. When the fish is evenly golden all over, remove and drain on brown paper sacks."],
    },
    {
        "title": "Chicken Quase",
        "date": "2 October, 2020",
        "img": "https://i.ibb.co/k1KfzR9/blog-Post7.jpg",
        "shortDesc": "Javanese deep-fried dish of chicken, tofu, or tempeh. The cooking method started as a means to preserve food. Chicken, tofu, and tempeh are first simmered in spice broth until fully cooked, tender, and the spices absorbed...",
        "rating": "5",
        "PrepTime": "25 minutes",
        "CookTime": "15 minutes",
        "TotalTime": "40 minutes",
        "Servings": "6",
        "Ingredients": ["1 Star anise", "500 gms basmati rice, blanched", "2 Bay leaves", "2 Black cardamom", "2 tsp black cumin seeds", "6 Black peppercorn", "6 Green cardamom", "2 Cinnamon sticks", "6 Cloves", "1 tsp fennel", "1/4 Jaiphal", "1 Javitri", "3 tsp Salt", "1 kg mutton (cut in 2 inches pieces, preferably front leg part and avoid shoulder cut)", "1 tbsp garam masala",],
        "Directions": ["1.In a large bowl, mix lamb mince with few Tbsp of vinegar, fenugreek leaves.",
            "2.Then add garlic paste, ginger paste, salt and black pepper as per taste.", "3.Add chopped coriander leaves and green chillies.", "4.Refrigerate the meat mixture, covered, to marinate for at least 5 hours.", "5.About 25 minutes before serving, shape the meat mixture into long 'tubes' around the skewers (seekhs) and place on to a grill over a drip tray or into the pre-heated oven (also on a drip tray) and bake for 20-25 minutes.", "6.Brush them with oil and cook for another 2 minutes.", "7.Using oven mittens or a cloth, carefully push the kebab from one end, on to a serving dish.", "8.Garnish with the chaat masala, onions, lemons and serve along with green chutney."
        ],
    },
    {
        "title": "Chicken nuggets",
        "date": "25 June, 2020",
        "img": "https://i.ibb.co/6HYv0vm/blog-Post8.jpg",
        "shortDesc": "Chicken nuggets are so wonderfully versatile, and they’re just as suitable for a quick after-school dinner for the kids as they are as a more grown up meal for adults. After all, who doesn’t love a morsel of tender, moist chicken, encased in a tasty batter or breadcrumb...",
        "rating": "4.6",
        "PrepTime": "20 minutes",
        "CookTime": "20 minutes",
        "TotalTime": "40 minutes",
        "Servings": "4",
        "Ingredients": ["1/2 cup all-purpose flour", "1 teaspoon granulated garlic", "Kosher salt and ground black pepper", "2 boneless skinless chicken breasts, cut into 1 1/2-inch pieces", "1 cup prepared breadcrumbs", "1 large egg", "1 cup vegetable oil"],
        "Directions": ["1. Place the flour in a resealable plastic bag and season with the garlic, 1 teaspoon salt and 1/4 teaspoon pepper. Place the chicken pieces in the bag with the flour and toss to coat (work in batches). Transfer the breadcrumbs to a rimmed plate, season with salt and pepper and set aside. ", "2. Whisk the egg and 1 tablespoon water in a medium bowl. Remove a piece of chicken from the flour, dip in the egg mixture, then the breadcrumbs, gently pressing the crumbs into the chicken, and set on a clean plate. Repeat with the remaining pieces of chicken. ", "3. Heat the vegetable oil in a large frying pan over medium-high heat. Add the chicken pieces to the pan (work in batches if needed) and brown on each side, about 8 minutes total. Use a spatula to transfer the chicken nuggets to a paper-towel-lined plate. Salt while hot and serve."],
    },
    {
        "title": "Nut dinner recipes",
        "date": "27 March, 2020",
        "img": "https://i.ibb.co/cNpw8xC/blog-Post9.jpg",
        "shortDesc": "Add nuts to your side dishes. Think of combinations like brown rice and chopped pecans, green beans and almonds, pistachios with peas and carrots. Nuts are so versatile; you can have a lot of fun being creative with them!...",
        "rating": "4.7",
        "PrepTime": "30 minutes",
        "CookTime": "10 minutes",
        "TotalTime": "40 minutes",
        "Servings": "3",
        "Ingredients": ["1/2 cup butter, melted", "1/2 cup confectioners' sugar", "1-1/2 teaspoons ground cinnamon", "1/4 teaspoon ground ginger", "1/4 teaspoon ground allspice", "1-1/2 cups pecan halves", "1-1/2 cups walnut halves", "1 cup unblanched almonds"],
        "Directions": ["1. In a greased 3-qt. slow cooker, mix butter, confectioners' sugar and spices. Add nuts; toss to coat. Cook, covered, on low 2-3 hours or until nuts are crisp, stirring once.", "2. Transfer nuts to waxed paper to cool completely. Store in an airtight container."],
    },
    {
        "title": "Roti & Roll",
        "date": "05 January, 2020",
        "img": "https://i.ibb.co/xgjmbry/blog-Post10.jpg",
        "shortDesc": "Paratha is made plain simple or stuffed with vegetable stuffings. The vegetables are mashed or finely chopped or grated. The stuffing can be mixed with the dough or layered as a single filling inside the dough...",
        "rating": "4.8",
        "PrepTime": "20 minutes",
        "CookTime": "20 minutes",
        "TotalTime": "40 minutes",
        "Servings": "4",
        "Ingredients": ["flour - 2 cup", "sugar - 1 tsp", "baking powder - 1/2 tsp", "oil - 2 tbsp", "salt - 1/2 tsp", "water to mix", "eggs - 6, lightly beaten", "oil - 2 tbsp", "onion - 1 cup, finely chopped", "chilli powder - 1 tsp", "turmeric powder - 1/2 tsp", "cumin powder - 1/2 tsp coriander powder - 1 tsp", "Garam Masala powder - 1 tsp", "tomato puree - 2 tbsp", "paneer - 150 gm, grated", "coriander leaves - 3 tbsp, chopped", "salt to taste"],
        "Directions": ["1. Combine flour, salt, sugar, baking powder and oil. Add enough water and knead into soft but not sticky dough. Keep covered for one and a halfhour. Heat oil for filling, fry onion till light brown. fry for few seconds. Add tomato puree, paneer, eggs and salt.", "2. Cook and stir on a low flame till the eggs are scrambled. Remove from fire and stir in the coriander leaves. Divide the dough into 8 parts. Roll out into thin rounds.", "3. Heat a girdle and cook the Roti slightly on both sides. Place 1/8 th of filling on each Roti and roll up. Seal the edges with some beaten egg. Brush the Rotis with egg and roll in peanut powder. Place them on a greased baking sheet, seam side down. Brush on top with oil and bake in a hot oven (200 C) till golden brown. Serve hot."],
    },
    {
        "title": "Mini Burger",
        "date": "25 October, 2019",
        "img": "https://i.ibb.co/KyBKsB1/blog-Post11.jpg",
        "shortDesc": "A simple combination of mayo and yellow mustard is what we use to grill and assemble the burgers. Cheese – we love thick-sliced medium cheddar cheese for burgers...",
        "rating": "4.5",
        "PrepTime": "15 minutes",
        "CookTime": "15 minutes",
        "TotalTime": "30 minutes",
        "Servings": "1",
        "Ingredients": ["6 guajillo peppers", "3 cloves garlic", "2 avocados, chopped", "1 lime, juiced", "1 jalapeno pepper, diced", "2 Tbsp chopped fresh cilantro", "1 ½ tsp salt, divided", "2 Tbsp chopped onion", "1 cup water", "1 Tbsp brown sugar", "1 Tbsp tomato paste", "1 Tbsp cider vinegar", "1 ancho chili, toasted and ground (or chili powder)", "1 lb ground beef", "1 tsp pepper", "8 slices queso fresco", "4 burger buns", "Tortilla chips", "4 slices tomato", "4 slices onion"],
        "Directions": ["1. Heat a skillet on medium-high. Add guajillo peppers and toast for 5 minutes. Remove peppers and set aside. Place garlic in the pan, with skin still intact and toast on both sides until lightly charred, about 3 minutes. Remove and set aside.",
            "2. Cut the stems off the guajillo peppers and discard seeds. Use scissors to cut the peppers into small pieces in a medium bowl. Pour boiling water over top until the peppers are covered and set aside to rehydrate for 15 minutes.",
            "3. Meanwhile, make the jalapeno guacamole by mashing together the avocado, lime juice, diced jalapeno, cilantro and ¼ tsp salt. Set aside until serving.",
            "4. Once the guajillo peppers are rehydrated, remove the skins from the garlic and place in the container of a blender. Add chopped onion, water, brown sugar, tomato paste, cider vinegar and ¼ tsp salt. Strain the guajillo peppers and add them to the blender. Pulse on high until smooth, then pass the guajillo ketchup through a sieve. Discard the seeds and skin, and reserve the ketchup for serving.",
            "5. Preheat BBQ on high heat. Form the ground beef into 4 patties and season with ancho chili, remaining salt and pepper. Place on the grill and cook for 5 minutes per side or until medium-well. Add queso fresco once the burgers are flipped. Toast the buns for the final minute of cooking. Remove the buns and burgers and allow to rest for 3 minutes.",
            "6. To assemble, spread a spoonful of jalapeno guacamole on the bottom bun. Top with a handful of tortilla chips and place burger on top. Spoon guajillo ketchup on the burger, then top with one slice of tomato and onion. Smother in additional guajillo ketchup and finish with the top bun.",
        ]
    },
]